# WEssential 配置文件
# 配置文件版本号
config_version: 1

# WEssential 设置
wessential_setting:
  # 语言文件
  language_file: 'zh_cn.yml'

# 登录系统 设置
login_setting:
  # 启用注册、登录系统
  enable_login_system: true

# 游戏规则
game_rules:
  # 是否关闭苦力怕爆炸破坏地形
  disable_creeper_explode_the_map: true
  # 是否保护耕地不受踩踏
  protect_farmland: true
  # 在所有世界强制开启死亡不掉落及不掉经验的游戏规则
  # 注意：开启后如需再次关闭这个功能，还需要在每个世界里操作一次游戏规则
  keep_inventory_in_all_world: false

# 传送设置
teleport_setting:
  # 传送等待时间（秒）
  # 管理员没有等待时间
  teleport_waiting_time: 5
  # 传送冷却时间（秒）
  # 管理员没有冷却时间
  teleport_cooling_time: 60
  # 最大额外家
  # 除了默认的床位置可以 /home 返回，其他的家的数量
  max_other_home: 1