name: WEssential
version: 1.1
author: WickhamWei
main: io.github.wickhamwei.wessential.WEssentialMain
api-version: 1.16
load: STARTUP
commands:
  home:
    description: 回到床或者家的位置
    usage: /<command> [家的名字]
  sethome:
    description: 设置家（默认家会覆盖床的位置）
    usage: /<command> [家的名字]
  homelist:
    description: 查看所有家的位置
    usage: /<command>
  removehome:
    description: 移除自定义的家
    usage: /<command> <家的名字>
  tpall:
    description: 传送所有人到您身边（OP）
    usage: /<command>
  tpa:
    description: 请求传送到某人
    usage: /<command> <玩家的名字>
  tpaccept:
    description: 接受传送请求
    usage: /<command>
  back:
    description: 回到上一个位置
    usage: /<command>
  register:
    description: 注册
    usage: /<command> <密码> <重复一遍密码>
  login:
    description: 登录
    usage: /<command> <密码>
  changepassword:
    description: 修改密码
    usage: /<command> <新密码> <重复一遍新密码>
  add:
    description: 给箱子添加新用户
    usage: /<command> <玩家名字> [玩家名字]...
  setminors:
    description: 将用户设置为未成年
    usage: /<command> <玩家名字> [玩家名字]...
  isminors:
    description: 用户是否在未成年列表内
    usage: /<command> <玩家名字>
  minorslist:
    description: 查看被设置成未成年的玩家列表
    usage: /<command>
  removeminors:
    description: 将玩家取消设置为未成年人
    usage: /<command> <玩家名字> [玩家名字]...
  setres:
    description: 用木棍左右键选中两个地点后，设置领地
    usage: /<command> <领地名字>
  reslist:
    description: 您的所有领地
    usage: /<command>
  removeres:
    description: 移除领地
    usage: /<command> <领地名字>
