name: WEssential
version: 1.0
author: WickhamWei
main: io.github.wickhamwei.wessential.WEssentialMain
api-version: 1.16
load: STARTUP
commands:
  home:
    description: 回到床或者家的位置
    usage: /<command> [家的名字]
  sethome:
    description: 设置家（默认家会覆盖床的位置）
    usage: /<command> [家的名字]
  homelist:
    description: 查看所有家的位置
    usage: /<command>
  removehome:
    description: 移除自定义的家
    usage: /<command> <家的名字>
  tpa:
    description: 请求传送到某人
    usage: /<command> <玩家的名字>
  tpaccept:
    description: 接受传送请求
    usage: /<command>
  back:
    description: 回到上一个位置
    usage: /<command>
  register:
    description: 注册
    usage: /<command> <密码> <重复一遍密码>
  login:
    description: 登录
    usage: /<command> <密码>
  changepassword:
    description: 修改密码
    usage: /<command> <新密码> <重复一遍新密码>